config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  resources :categories
  resources :users
  get "search_users", to: 'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user

    has_many :article_categories
    has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/create_category.rb
class CreateCategory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    def show
        @article = Article.find(params[:id])
    end
    def new
        @article = Article.new
    end
    def create
        #byebug
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to articles_path
        else
            flash[:notice] = "Article was not created successfully."
            render 'new'
        end
    end
    def edit
        @article = Article.find(params[:id])
    end
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was created successfully."
            redirect_to articles_path
        else
            render 'edit'
        end
            
        
    end
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article was delete successfully."
        redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end
    def show
        @category = Category.find(params[:id])
    end
    def new
        @category = Category.new
    end
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was created successfully."
            redirect_to categories_path
        else
            render 'new'
        end
    end
    def edit
        @category = Category.find(params[:id])
    end
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Article was created successfully."
            redirect_to categories_path
        else
            render 'edit'
        end
            
        
    end
    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        flash[:notice] = "Category was delete successfully."
        redirect_to categories_path
    end

    private
    def category_params
        params.require(:category).permit(:name, article_ids: [] )
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end
    def new
        @user = User.new
    end
    def create
        byebug
        @user = User.new(article_params)
        if @user.save
            flash[:notice] = "Article was created successfully."
            redirect_to users_path
        else
            flash[:notice] = "Article was not created successfully."
            render 'new'
        end
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        if @user.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to users_path
        else
            render 'edit'
        end
            
        
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:notice] = "Article was delete successfully."
        redirect_to users_path
    end

    def search
        #byebug
        if params[:user].present?
            @user = User.where(name: params[:user]).first
            if @user
                flash[:alert] = "Found the name"
                redirect_to users_path
            else
                flash[:alert] = "Name not found"
                redirect_to users_path
            end
        else
            @users = User.all
            flash.now[:alert] = "Please enter a name to search"
            render "users/index"
        end
    end


    private
    def article_params
        params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>


<%= form_with model: @article do |form| %>
    <div>
    <%= form.label :title %>
    <%= form.text_field :title %>  
    </div>
    <div>
    <%= form.label :description %>
    <%= form.text_area :description %>  
    </div>
    <%= form.label :category %>
    <%= form.collection_select(:category_ids, Category.all,:id, :name,
      { prompt: "Make your selection"}, { multiple: true}) %>
    </div>
    <div>
    <%= form.submit%>
    </div>
<% end %>

<%= link_to 'Cancel', articles_path%>|
<%= link_to 'Category', categories_path%>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% @articles.each do |article| %>
    <ul>
        <li><%= article.title %></li>
        <li><%= article.description %></li>
        <li><% article.categories.each do |category| %>
            <ul> 
            <li><%= category.name %></li>
            </ul>
            <% end %>
            <%= link_to 'View', article_path(article)%>|
            <%= link_to 'Edit', edit_article_path(article)%>|
            <%= link_to 'Delete', article_path(article), method: :delete%>
        </li>

    </ul>
<% end %>

<%= link_to 'New article', new_article_path%> |
<%= link_to 'Categories', categories_path%> |
<%= link_to 'Users', users_path%>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= form_with model: @article do |form| %>
    <div>
    <%= form.label :title %>
    <%= form.text_field :title %>  
    </div>
    <div>
    <%= form.label :description %>
    <%= form.text_area :description %>  
    </div>
    <div>
    <%= form.label :category %>
    <%= form.collection_select(:category_ids, Category.all,:id, :name,
      { prompt: "Make your selection"}, { multiple: true}) %>
    </div>
    <div>
    <%= form.submit%>
    </div>
<% end %>

<%= link_to 'Cancel', articles_path%>|
<%= link_to 'Category', categories_path%>
            

app/views/articles/show.html.erb
<h1>Article</h1>
    <ul>
        <li><%= @article.title %></li>
        <li><%= @article.description %></li>
        <ul>
        <%= render @article.categories %>
        </ul>
    </ul>
    <%= link_to 'Articles', articles_path%>|
    <%= link_to 'Category', categories_path%>

app/views/categories/_category.html.erb
<li><%= category.name %></li>

app/views/categories/edit.html.erb
<h1>Edit category</h1>


<%= form_with model: @category do |form| %>
    <div>
    <%= form.label :name %>
    <%= form.text_field :name %>  
    </div>
    
    <div>
    <%= form.submit%>
    </div>
<% end %>

<%= link_to 'Cancel', articles_path%>|
<%= link_to 'Category', categories_path%>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |category| %>
    <ul>
        <li><%= category.name %>
        <li><% category.articles.each do |article| %>
            <ul> 
            <li>Articles: <%= article.title %></li>
            </ul>
            <% end %>
            <%= link_to 'View', category_path(category)%>|
            <%= link_to 'Edit', edit_category_path(category)%>|
            <%= link_to 'Delete', category_path(category), method: :delete%>
        </li>

    </ul>
<% end %>

<%= link_to 'New category', new_category_path%> |
<%= link_to 'Articles', articles_path%>|
<%= link_to 'Users', users_path%>

app/views/categories/new.html.erb
<h1>New category</h1>


<%= form_with model: @category do |form| %>
    <div>
    <%= form.label :name %>
    <%= form.text_field :name %>  
    </div>
    
    <div>
    <%= form.submit%>
    </div>
<% end %>

<%= link_to 'Cancel', articles_path%>|
<%= link_to 'Category', categories_path%>

app/views/categories/show.html.erb
<h1>Category</h1>
    <ul>
        <li><%= @category.name %></li>
        <h3>Articles:</h3>
        <li><% @category.articles.each do |article| %>
            <ul> 
            <li><%= article.title %></li>
            </ul>
            <% end %>
        
    </ul>
    <%= link_to 'Articles', articles_path%>|
    <%= link_to 'Categories', categories_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveRecord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %> 
      <%= msg %> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: obj do |form| %>
    <div>
    <%= form.label :name %>
    <%= form.text_field :name %>  
    </div>
    <div>
    <%= form.label :email %>
    <%= form.email_field :email %>  
    </div>

    <%= form.check_box :pet_dog %>
    <%= form.label :pet_dog, "I own a dog" %>
    <%= form.check_box :pet_cat %>
    <%= form.label :pet_cat, "I own a cat" %>

    <%= form.radio_button :age, "child" %>
    <%= form.label :age_child, "I am younger than 21" %>
    <%= form.radio_button :age, "adult" %>
    <%= form.label :age_adult, "I am over 21" %>

    <%= form.text_area :message, size: "70x5" %>
    <%= form.hidden_field :parent_id, value: "foo" %>
    <%= form.password_field :password %>
    <%= form.number_field :price, in: 1.0..20.0, step: 0.5 %>
    <%= form.range_field :discount, in: 1..100 %>
    <%= form.date_field :born_on %>
    <%= form.time_field :started_at %>
    <%= form.datetime_local_field :graduation_day %>
    <%= form.month_field :birthday_month %>
    <%= form.week_field :birthday_week %>
    <%= form.search_field :name %>
    <%= form.email_field :address %>
    <%= form.telephone_field :phone %>
    <%= form.url_field :homepage %>
    <%= form.color_field :favorite_color %>
       
    <div>
    <%= form.submit%>
    </div>
<% end %>

<%= form_with model: obj do |person_form| %>
    <%= person_form.text_field :name %>
    <%= fields_for :contact_detail, obj.name do |contact_detail_form| %>
      <%= contact_detail_form.text_field :phone_number %>
    <% end %>
  <% end %>

app/views/users/_search_user.html.erb
<%= form_with url: search_users_path, method: :get do |form| %>
    <%= form.label :user, "Search for:" %>
    <%= form.text_field :user %>
    <%= form.submit "Search" %>
  <% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render partial: "form", locals: {obj: @user} %>

<%= link_to 'Cancel', users_path%>|
<%= link_to 'Category', categories_path%>

app/views/users/index.html.erb
<h1>Users</h1>

<%= render "search_user" %>

<% @users.each do |user| %>
    <ul>
        <li><%= user.name %></li>
        <li><%= user.email %>
            <%= link_to 'View', user_path(user)%>|
            <%= link_to 'Edit', edit_user_path(user)%>|
            <%= link_to 'Delete', user_path(user), method: :delete%>
        </li>

    </ul>
<% end %>
<%= link_to 'Articles', articles_path%>|
    <%= link_to 'Categories', categories_path%>|
    <%= link_to 'New User', new_user_path%>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render partial: "form", locals: {obj: @user} %>

<%= link_to 'Cancel', users_path%>|
<%= link_to 'Category', categories_path%>
            

app/views/users/show.html.erb
<h1>User</h1>

    <ul>
        <li><%= @user.name %></li>
        <li><%= @user.email %>
            
        </li>

    </ul>
    <%= link_to 'Articles', articles_path%>|
    <%= link_to 'Categories', categories_path%>|
    <%= link_to 'Users', users_path%>